#' Bootstrap Transmission Rates
#'
#' This function extracts bootstraps samples of the mean number of transmissions per person.
#'
#' @param results MCMC output as generated by run_mcmc.
#' @param N_samples The number of bootstrap samples to draw.
#' @param uncorrelate If using correlated results, should we first uncorrelate them? (Defualts to TRUE.)
#' @param burnin We discard the first (burnin * 100) percent of the results, if running uncorrelation.
#' @param plot_ci Should we plot the bootstrap confidence intervals of the number of transmissions per person? (Defaults to TRUE.)
#' @return A N_samples x (N + 1) matrix, where N is the number of hosts in the outbreak, and the additional column reports the number of index cases. Each row is one bootstrap sample of the mean number of transmissions per person (or mean number of index cases).
#' @export

# MIT License
#
# Copyright (c) 2023 Ivan Specht
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
#   The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

bootstrap_transmission <- function(results, N_samples, uncorrelate = T, burnin = 0.1, plot_ci = T){
  if(uncorrelate){
    if(is.null(results[[1]]$uncorrelated)){
      results <- uncorrelate(results, burnin = burnin)
    }
  }else{
    if(is.null(results[[1]]$uncorrelated)){
      warning("It is highly recommended to use uncorrelate = TRUE when calling bootstrap_transmission() on correlated MCMC samples.")
    }
  }

  N <- results[[1]]$N
  out <- matrix(nrow = 0, ncol = N)
  for (i in 1:N_samples) {
    indices <- sample(1:length(results), length(results), replace = T)
    boot <- results[indices]
    ancestry <- rep(0, N)
    for (j in 1:length(results)) {
      ancestry <- ancestry + sapply(1:N, function(x){sum(boot[[j]]$anc == x, na.rm = T)})
    }
    ancestry <- ancestry / length(results)
    out <- rbind(out, ancestry)
  }

  if(plot_ci){
    p_data <- reshape2::melt(out)[,2:3]
    p_data$Var2 <- paste(p_data$Var2)
    p_data$Var2[p_data$Var2 == "1"] <- "Index"
    colnames(p_data)[1] <- "Host"
    p_data$Host <- factor(p_data$Host, levels = c("Index", paste(2:N)))

    print(ggplot2::ggplot(p_data, ggplot2::aes(x = Host, y = value)) +
      ggplot2::geom_boxplot(outlier.size=-1, color = "#2255BB", fill = "#AACCEE") +
      ggplot2::ylab("Number of Transmissions") +
      ggplot2::theme_minimal())
  }

  colnames(out) <- c("Index", paste(2:N))
  rownames(out) <- NULL
  return(out)
}









