#' SNP Distance Matrix
#'
#' This function returns a SNP distance matrix based on the FASTA input.
#'
#' @param results MCMC output as generated by run_mcmc.
#' @return A matrix.
#' @export

# MIT License
#
# Copyright (c) 2023 Ivan Specht
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
#   The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

distance <- function(
    results
){
  N <- results[[1]]$N
  out <- matrix(nrow = N, ncol = N)
  for (i in 1:N) {
    for (j in 1:N) {
      out[i,j] <- get_cons_dist(i, j, results[[1]]$reads)
    }
  }
  diag(out) <- NA
  out <- out[2:N, 2:N]
  colnames(out) <- 2:N
  rownames(out) <- 2:N
  return(out)
}
