#' Tabulate MCMC Output
#'
#' This function creates a table of the posterior probabilities associated with each possible transmission link.
#'
#' @param results MCMC output as generated by run_mcmc.
#' @param burnin We discard the first (burnin * 100) percent of the results
#' @return A data frame.
#' @export

# MIT License
#
# Copyright (c) 2023 Ivan Specht
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
#   The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

tabulate <- function(
    results,
    burnin = 0.1 # we should discard the first (burnin * 100) percent of the results
){

  N <- results[[1]]$N
  reads <- results[[1]]$reads

  adj <- matrix(0, nrow = N, ncol = N)

  for (i in 1:length(results)) {
    if(i > burnin*length(results)){
      inds <- cbind(results[[i]]$anc[2:N], 2:N)
      adj[inds] <- adj[inds] + 1
    }
  }

  adj <- adj / (sum(1:length(results) > burnin*length(results)))

  adj_melt <- reshape2::melt(adj)
  adj_melt <- adj_melt[adj_melt$value > 0, ]
  colnames(adj_melt) <- c("From_Alias", "To_Alias", "Probability")
  adj_melt$Distance <- mapply(get_cons_dist, adj_melt$From, adj_melt$To, MoreArgs = list(reads=reads))
  adj_melt$Relationship <- mapply(summarize, adj_melt$From, adj_melt$To, MoreArgs = list(reads=reads))
  adj_melt[,1] <- paste(adj_melt[,1])
  adj_melt[,2] <- paste(adj_melt[,2])
  adj_melt[,1][adj_melt[,1] == "1"] <- "Index"
  rownames(adj_melt) <- NULL

  dec <- decipher(results)
  From_Name <- adj_melt$From_Alias
  From_Name[From_Name != "Index"] <- dec$Name[match(From_Name[From_Name != "Index"], paste(dec$Alias))]
  To_Name <- adj_melt$To_Alias
  To_Name <- dec$Name[match(To_Name, paste(dec$Alias))]
  adj_melt <- cbind(cbind(From_Name, To_Name), adj_melt)

  return(adj_melt)

}





