#' Extract Uncorrelated Posterior Samples
#'
#' This function extracts uncorrelated posterior samples of an outbreak.
#'
#' @param results MCMC output as generated by run_mcmc.
#' @param burnin We discard the first (burnin * 100) percent of the results
#' @return An uncorrelated Markov chain, of the same format as the "results" input.
#' @export

# MIT License
#
# Copyright (c) 2023 Ivan Specht
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
#   The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

uncorrelate <- function(results, burnin = 0.1){
  # Delete burnin period
  results <- results[1:length(results) > burnin*length(results)]

  # Log-posterior density
  tr <- c()
  for (i in 1:length(results)) {
    tr <- c(tr, sum(results[[i]]$g_lik) + results[[i]]$e_lik + sum(results[[i]]$u_lik))
  }

  # IAT (rounded up)
  capture.output(iat <- ceiling(LaplacesDemon::IAT(tr)))
  results <- results[seq(1, length(results), iat)]

  # Make a note that we've uncorrelated the samples
  results[[1]]$uncorrelated <- T

  return(results)
}
